# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: graciano codes
email: matheusgraciano@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Matheus Graciano: Escritor de software, rubro negro e músico. Cara esquisito de exatas que lê poesia. Grande apreciador de batidas de limão.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graciano.me" # the base hostname & protocol for your site
github_username: graciano
timezone: America/Sao_Paulo
show_excerpts: true
lang: pt-BR
instagram_username: wtfgraciano
twitter:
  username: wtfgraciano
  card: summary

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-gist

disqus:
  shortname: graciano

assets:

  assets:
    - "*.png"
    - "*.jpg"
    - "*.woff2"
    - "*.otf"

  autoprefixer:
    browsers: ["last 2 versions","> 5%"]

  sources:
    # - _assets/img
    - _assets/stylesheets

pagination:
  enabled: true
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  per_page: 3
  permalink: 'pagina/:num/' # TEM QUE TER BARRA NO FINAL AQUI !!!
  title: ':title - página :num'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
